### PR TITLE
Processes with spaces are no longer filtered out

### PR DESCRIPTION
**Pull request by yoiang**
Addresses issue #11

### CODE REVIEW

**Comment by danielkrainas** [comment]
Thanks for the submission and sorry for the delay in response, just getting back online after hurricane Matthew. I'll merge and publish this later tonight after I add a test for the case mentioned in #11

**Comment by yoiang** [comment]
No worries! Were you effected severely?

**Comment by danielkrainas** [comment]
Nothing bad thankfully, power out for a day and internet down for a couple days.

**Comment by danielkrainas** [comment]
Released in [v1.3.2](https://github.com/danielkrainas/node-netstat/releases/tag/v1.3.2)

**Comment by yoiang** [comment]
I'm glad to hear

**Pull request merged**
